// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuthEvents = `-- name: ListAuthEvents :many
SELECT id, actor_user_id, tenant_id, action, target_type, target_id, metadata, created_at FROM audit_logs
WHERE action IN ('auth.login', 'auth.logout')
ORDER BY created_at DESC, id DESC
LIMIT $1
`

// Login/logout terbaru (subset audit_logs) untuk tabel aktivitas panel.
func (q *Queries) ListAuthEvents(ctx context.Context, pageSize int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuthEvents, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.TenantID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const presenceByDay = `-- name: PresenceByDay :many
SELECT
    (date_trunc('day', bucket_at AT TIME ZONE $1::text))::date AS day_local,
    COALESCE(count(DISTINCT user_id), 0)::bigint AS active_users,
    COALESCE(sum(hits), 0)::bigint             AS total_hits
FROM activity_presence
WHERE bucket_at >= $2::timestamptz
  AND bucket_at <  $3::timestamptz
GROUP BY day_local
ORDER BY day_local
`

type PresenceByDayParams struct {
	Tz     string             `json:"tz"`
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type PresenceByDayRow struct {
	DayLocal    pgtype.Date `json:"day_local"`
	ActiveUsers int64       `json:"active_users"`
	TotalHits   int64       `json:"total_hits"`
}

// Tren per HARI-LOKAL untuk rentang mingguan/bulanan (line chart).
func (q *Queries) PresenceByDay(ctx context.Context, arg PresenceByDayParams) ([]PresenceByDayRow, error) {
	rows, err := q.db.Query(ctx, presenceByDay, arg.Tz, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresenceByDayRow{}
	for rows.Next() {
		var i PresenceByDayRow
		if err := rows.Scan(&i.DayLocal, &i.ActiveUsers, &i.TotalHits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const presenceByHour = `-- name: PresenceByHour :many
SELECT
    extract(hour FROM bucket_at AT TIME ZONE $1::text)::int AS hour_local,
    COALESCE(count(DISTINCT user_id), 0)::bigint AS active_users,
    COALESCE(sum(hits), 0)::bigint             AS total_hits
FROM activity_presence
WHERE bucket_at >= $2::timestamptz
  AND bucket_at <  $3::timestamptz
GROUP BY hour_local
ORDER BY hour_local
`

type PresenceByHourParams struct {
	Tz     string             `json:"tz"`
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type PresenceByHourRow struct {
	HourLocal   int32 `json:"hour_local"`
	ActiveUsers int64 `json:"active_users"`
	TotalHits   int64 `json:"total_hits"`
}

// Distribusi aktivitas per JAM-LOKAL untuk satu rentang (bar "aktivitas per jam").
// AT TIME ZONE mengonversi bucket UTC ke jam lokal. Handler mengisi jam kosong
// jadi 0 (sumbu X ECharts butuh 0..23 lengkap). COALESCE+cast: SUM/COUNT nullable
// → paksa int64 (bukan pgtype.Numeric).
func (q *Queries) PresenceByHour(ctx context.Context, arg PresenceByHourParams) ([]PresenceByHourRow, error) {
	rows, err := q.db.Query(ctx, presenceByHour, arg.Tz, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresenceByHourRow{}
	for rows.Next() {
		var i PresenceByHourRow
		if err := rows.Scan(&i.HourLocal, &i.ActiveUsers, &i.TotalHits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const presenceKPIs = `-- name: PresenceKPIs :one
SELECT
    COALESCE(count(DISTINCT user_id), 0)::bigint AS active_users,
    COALESCE(sum(hits), 0)::bigint             AS total_hits
FROM activity_presence
WHERE bucket_at >= $1::timestamptz
  AND bucket_at <  $2::timestamptz
`

type PresenceKPIsParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type PresenceKPIsRow struct {
	ActiveUsers int64 `json:"active_users"`
	TotalHits   int64 `json:"total_hits"`
}

// KPI ringkas untuk stat cards pada rentang aktif.
func (q *Queries) PresenceKPIs(ctx context.Context, arg PresenceKPIsParams) (PresenceKPIsRow, error) {
	row := q.db.QueryRow(ctx, presenceKPIs, arg.FromAt, arg.ToAt)
	var i PresenceKPIsRow
	err := row.Scan(&i.ActiveUsers, &i.TotalHits)
	return i, err
}

const presenceUserSpans = `-- name: PresenceUserSpans :many
SELECT
    ap.user_id,
    u.email,
    min(ap.bucket_at)::timestamptz    AS first_seen,
    max(ap.last_seen_at)::timestamptz AS last_seen,
    COALESCE(sum(ap.hits), 0)::bigint  AS total_hits
FROM activity_presence ap
JOIN users u ON u.id = ap.user_id
WHERE ap.bucket_at >= $1::timestamptz
  AND ap.bucket_at <  $2::timestamptz
GROUP BY ap.user_id, u.email
ORDER BY first_seen
`

type PresenceUserSpansParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type PresenceUserSpansRow struct {
	UserID    int64              `json:"user_id"`
	Email     string             `json:"email"`
	FirstSeen pgtype.Timestamptz `json:"first_seen"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	TotalHits int64              `json:"total_hits"`
}

// "User aktif jam berapa s/d jam berapa" untuk rentang: first/last seen per user +
// total hit. JOIN users untuk email TAMPILAN panel (dev-only UI, bukan log — tabel
// activity_presence sendiri hanya simpan user_id). first/last dikembalikan sebagai
// timestamptz UTC; handler memformatnya ke jam lokal (appTZ) — lebih bersih dari
// AT TIME ZONE di SQL (yang bikin sqlc emit interface{}).
func (q *Queries) PresenceUserSpans(ctx context.Context, arg PresenceUserSpansParams) ([]PresenceUserSpansRow, error) {
	rows, err := q.db.Query(ctx, presenceUserSpans, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresenceUserSpansRow{}
	for rows.Next() {
		var i PresenceUserSpansRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.FirstSeen,
			&i.LastSeen,
			&i.TotalHits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPresence = `-- name: RecordPresence :exec
INSERT INTO activity_presence (user_id, bucket_at, hits, last_seen_at, tenant_id)
VALUES (
    $1::bigint,
    to_timestamp(floor(extract(epoch FROM now()) / 900) * 900),
    1, now(),
    $2::bigint
)
ON CONFLICT (user_id, bucket_at)
DO UPDATE SET hits = activity_presence.hits + 1, last_seen_at = now()
`

type RecordPresenceParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

// Presence bucket 15-menit. bucket_at di-floor SERVER-SIDE ke kelipatan 900 dtk
// (jangan hitung di Go — hindari drift clock). Agregasi di level baris: request
// berulang dalam bucket sama hanya menaikkan hits, bukan insert baris baru.
func (q *Queries) RecordPresence(ctx context.Context, arg RecordPresenceParams) error {
	_, err := q.db.Exec(ctx, recordPresence, arg.UserID, arg.TenantID)
	return err
}
