// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_user_id, action, target_type, target_id, metadata, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_user_id, tenant_id, action, target_type, target_id, metadata, created_at
`

type CreateAuditLogParams struct {
	ActorUserID *int64 `json:"actor_user_id"`
	Action      string `json:"action"`
	TargetType  string `json:"target_type"`
	TargetID    *int64 `json:"target_id"`
	Metadata    []byte `json:"metadata"`
	TenantID    *int64 `json:"tenant_id"`
}

// Jejak aksi admin. metadata TANPA PII (id saja, bukan email/nama).
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.TenantID,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.TenantID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_user_id, tenant_id, action, target_type, target_id, metadata, created_at FROM audit_logs
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListAuditLogs(ctx context.Context, pageSize int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.TenantID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
