// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE invites SET accepted_at = now()
WHERE token = $1 AND accepted_at IS NULL AND expires_at > now()
`

// Tandai terpakai (one-time). Guard accepted_at IS NULL → race dua klik tak
// menghasilkan dua membership (UNIQUE di memberships jadi jaring kedua).
func (q *Queries) AcceptInvite(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, acceptInvite, token)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (tenant_id, email, role, token, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, email, role, token, invited_by, accepted_at, expires_at, created_at
`

type CreateInviteParams struct {
	TenantID  int64              `json:"tenant_id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Token     string             `json:"token"`
	InvitedBy *int64             `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Undangan bergabung ke workspace. token = rahasia URL (crypto/rand hex via
// oauth.NewState). email boleh milik orang yang BELUM punya akun.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1 AND tenant_id = $2
`

type DeleteInviteParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

// Batalkan undangan yang belum diterima.
func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.TenantID)
	return err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT i.id, i.tenant_id, i.email, i.role, i.token, i.invited_by, i.accepted_at, i.expires_at, i.created_at, t.name AS tenant_name, t.slug AS tenant_slug
FROM invites i
JOIN tenants t ON t.id = i.tenant_id
WHERE i.token = $1
`

type GetInviteByTokenRow struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	Token      string             `json:"token"`
	InvitedBy  *int64             `json:"invited_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantName string             `json:"tenant_name"`
	TenantSlug string             `json:"tenant_slug"`
}

// Jalur PUBLIK (/invite/{token}) — penerima belum tentu login/anggota. Validasi
// kedaluwarsa & sudah-dipakai dilakukan di handler agar pesannya spesifik.
func (q *Queries) GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i GetInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TenantName,
		&i.TenantSlug,
	)
	return i, err
}

const listInvitesByTenant = `-- name: ListInvitesByTenant :many
SELECT id, tenant_id, email, role, token, invited_by, accepted_at, expires_at, created_at FROM invites
WHERE tenant_id = $1 AND accepted_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

// Undangan PENDING satu workspace (panel anggota) — yang sudah diterima disaring.
func (q *Queries) ListInvitesByTenant(ctx context.Context, tenantID int64) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvitesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.AcceptedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
