// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnedWorkspaces = `-- name: CountOwnedWorkspaces :one
SELECT count(*)::bigint
FROM memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.user_id = $1 AND m.role = 'owner' AND t.deleted_at IS NULL
`

// Berapa workspace yang DIMILIKI user (role owner) — untuk cek kuota sebelum
// membuat workspace baru. Diundang jadi member/admin TIDAK memakan kuota.
//
// Workspace TERHAPUS tak dihitung (0005 §7): kuota yang masih tertahan oleh
// workspace yang sudah dihapus terasa seperti bug, dan mendorong user memurge
// lebih cepat — kebalikan dari tujuan masa tenggang. Yang TERARSIP TETAP
// dihitung: datanya masih disimpan & bisa diaktifkan kapan saja.
func (q *Queries) CountOwnedWorkspaces(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedWorkspaces, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTenantOwners = `-- name: CountTenantOwners :one
SELECT count(*)::bigint FROM memberships WHERE tenant_id = $1 AND role = 'owner'
`

// Jumlah owner di satu workspace — cegah menghapus/menurunkan owner terakhir
// (workspace tanpa owner = yatim).
func (q *Queries) CountTenantOwners(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantOwners, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (user_id, tenant_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, tenant_id) DO NOTHING
RETURNING id, user_id, tenant_id, role, created_at
`

type CreateMembershipParams struct {
	UserID   int64  `json:"user_id"`
	TenantID int64  `json:"tenant_id"`
	Role     string `json:"role"`
}

// Jadikan user anggota workspace dgn role tertentu. Dipakai: register/OAuth (owner
// workspace pertama), buat workspace baru (owner), terima invite (admin/member).
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.TenantID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE user_id = $1 AND tenant_id = $2
`

type DeleteMembershipParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

// Keluarkan anggota dari workspace (atau user keluar sendiri).
func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.TenantID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, tenant_id, role, created_at FROM memberships WHERE user_id = $1 AND tenant_id = $2
`

type GetMembershipParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

// Validasi keanggotaan — dipakai middleware Scope SEBELUM membuka tx ber-tenant
// (memastikan tenant aktif di session memang milik user; anti tenant-forcing).
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.TenantID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembersByTenant = `-- name: ListMembersByTenant :many
SELECT m.id, m.user_id, m.role, m.created_at, u.email, u.avatar_url, u.status
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1 AND u.deleted_at IS NULL
ORDER BY m.created_at, m.id
`

type ListMembersByTenantRow struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Email     string             `json:"email"`
	AvatarUrl *string            `json:"avatar_url"`
	Status    string             `json:"status"`
}

// Daftar anggota SATU workspace (panel /admin/members). JOIN users untuk email
// tampilan — users kini tabel global (tanpa RLS), jadi filter tenant di sini.
func (q *Queries) ListMembersByTenant(ctx context.Context, tenantID int64) ([]ListMembersByTenantRow, error) {
	rows, err := q.db.Query(ctx, listMembersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByTenantRow{}
	for rows.Next() {
		var i ListMembersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.AvatarUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT m.tenant_id, m.role, t.name, t.slug, t.status
FROM memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.user_id = $1 AND t.deleted_at IS NULL
ORDER BY m.created_at, m.id
`

type ListMembershipsByUserRow struct {
	TenantID int64  `json:"tenant_id"`
	Role     string `json:"role"`
	Name     string `json:"name"`
	Slug     string `json:"slug"`
	Status   string `json:"status"`
}

// Daftar workspace milik user (untuk switcher sidebar). Urut terlama dulu agar
// workspace pertama (dari register) jadi default stabil.
//
// Workspace TERHAPUS disembunyikan (0005): ia juga jadi sumber pilihan fallback
// middleware Scope, jadi tanpa filter ini user bisa dilempar ke workspace yang
// sudah dihapus. status ikut dikembalikan agar switcher bisa menandai yang
// suspended/archived alih-alih membiarkan user menabrak 403 setelah mengklik.
func (q *Queries) ListMembershipsByUser(ctx context.Context, userID int64) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Role,
			&i.Name,
			&i.Slug,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForUsers = `-- name: ListMembershipsForUsers :many
SELECT m.user_id, m.tenant_id, m.role, t.name, t.slug
FROM memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.user_id = ANY($1::bigint[]) AND t.deleted_at IS NULL
ORDER BY m.user_id, m.created_at, m.id
`

type ListMembershipsForUsersRow struct {
	UserID   int64  `json:"user_id"`
	TenantID int64  `json:"tenant_id"`
	Role     string `json:"role"`
	Name     string `json:"name"`
	Slug     string `json:"slug"`
}

// Membership BANYAK user sekaligus (panel /dev: tampilkan workspace+role tiap
// user). Satu query untuk semua id → hindari N+1 (Rule 13).
func (q *Queries) ListMembershipsForUsers(ctx context.Context, userIds []int64) ([]ListMembershipsForUsersRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUsersRow{}
	for rows.Next() {
		var i ListMembershipsForUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.TenantID,
			&i.Role,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE memberships SET role = $3 WHERE user_id = $1 AND tenant_id = $2
`

type UpdateMemberRoleParams struct {
	UserID   int64  `json:"user_id"`
	TenantID int64  `json:"tenant_id"`
	Role     string `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.UserID, arg.TenantID, arg.Role)
	return err
}
