// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityPresence struct {
	UserID     int64              `json:"user_id"`
	BucketAt   pgtype.Timestamptz `json:"bucket_at"`
	Hits       int32              `json:"hits"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	TenantID   int64              `json:"tenant_id"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	ActorUserID *int64             `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    *int64             `json:"target_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TenantID    int64              `json:"tenant_id"`
}

type Invite struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	Token      string             `json:"token"`
	InvitedBy  *int64             `json:"invited_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TenantID  int64              `json:"tenant_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OauthAccount struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Provider    string             `json:"provider"`
	ProviderUid string             `json:"provider_uid"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TenantID    int64              `json:"tenant_id"`
}

type PlatformStaff struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             int64              `json:"id"`
	Email          string             `json:"email"`
	PassHash       *string            `json:"pass_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EmailVerified  bool               `json:"email_verified"`
	Status         string             `json:"status"`
	AvatarUrl      *string            `json:"avatar_url"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	WorkspaceQuota int32              `json:"workspace_quota"`
}
