// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthAccount struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Provider    string             `json:"provider"`
	ProviderUid string             `json:"provider_uid"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Todo struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Title     string             `json:"title"`
	Done      bool               `json:"done"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            int64              `json:"id"`
	Email         string             `json:"email"`
	PassHash      *string            `json:"pass_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	EmailVerified bool               `json:"email_verified"`
}
