// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::bigint FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

// Badge sidebar — dirender di SETIAP halaman, ditopang index partial
// idx_notif_unread agar tak menyentuh baris yang sudah terbaca.
func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, tenant_id, kind, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, tenant_id, kind, payload, read_at, created_at
`

type CreateNotificationParams struct {
	UserID   int64  `json:"user_id"`
	TenantID *int64 `json:"tenant_id"`
	Kind     string `json:"kind"`
	Payload  []byte `json:"payload"`
}

// Dipanggil saat peristiwa keanggotaan terjadi (role diubah, dikeluarkan).
// payload = snapshot detail siap-render; lihat migrasi 00009.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.TenantID,
		arg.Kind,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Kind,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.user_id, n.tenant_id, n.kind, n.payload, n.read_at, n.created_at, t.name AS tenant_name
FROM notifications n
LEFT JOIN tenants t ON t.id = n.tenant_id
WHERE n.user_id = $1
  AND (n.created_at, n.id) < ($2::timestamptz, $3::bigint)
ORDER BY n.created_at DESC, n.id DESC
LIMIT $4
`

type ListNotificationsParams struct {
	UserID          int64              `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListNotificationsRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TenantID   *int64             `json:"tenant_id"`
	Kind       string             `json:"kind"`
	Payload    []byte             `json:"payload"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantName *string            `json:"tenant_name"`
}

// Keyset pagination (pola ListUsers) — cast ::timestamptz/::bigint WAJIB, tanpa
// itu sqlc salah infer tipe cursor_id pada row-value comparison.
//
// `user_id = $1` BUKAN sekadar filter tampilan: notifications sengaja TANPA RLS
// (lihat 00009), jadi klausa ini adalah SATU-SATUNYA penjaga isolasi antar-user.
// Jangan pernah menghapusnya "karena sudah difilter di Go".
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Kind,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

// Auto-read saat halaman dibuka. Undangan TIDAK tersentuh di sini — memang tak
// disimpan di tabel ini (sumber kebenarannya tetap `invites`), sehingga undangan
// pending tetap terhitung di badge sampai benar-benar ditindak.
func (q *Queries) MarkNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, userID)
	return err
}
