// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (user_id, provider, provider_uid, tenant_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_uid, created_at, tenant_id
`

type CreateOAuthAccountParams struct {
	UserID      int64  `json:"user_id"`
	Provider    string `json:"provider"`
	ProviderUid string `json:"provider_uid"`
	TenantID    int64  `json:"tenant_id"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUid,
		arg.TenantID,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_uid, created_at, tenant_id FROM oauth_accounts WHERE provider = $1 AND provider_uid = $2
`

type GetOAuthAccountParams struct {
	Provider    string `json:"provider"`
	ProviderUid string `json:"provider_uid"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderUid)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const listOAuthAccountsByUser = `-- name: ListOAuthAccountsByUser :many
SELECT id, user_id, provider, provider_uid, created_at, tenant_id FROM oauth_accounts WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListOAuthAccountsByUser(ctx context.Context, userID int64) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, listOAuthAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAccount{}
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUid,
			&i.CreatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
