// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Tandai terpakai (one-time). Guard accepted_at IS NULL → race dua klik tak
	// menghasilkan dua membership (UNIQUE di memberships jadi jaring kedua).
	AcceptInvite(ctx context.Context, token string) error
	AddPlatformStaff(ctx context.Context, email string) (PlatformStaff, error)
	// Berapa workspace yang DIMILIKI user (role owner) — untuk cek kuota sebelum
	// membuat workspace baru. Diundang jadi member/admin TIDAK memakan kuota.
	CountOwnedWorkspaces(ctx context.Context, userID int64) (int64, error)
	// Jumlah owner di satu workspace — cegah menghapus/menurunkan owner terakhir
	// (workspace tanpa owner = yatim).
	CountTenantOwners(ctx context.Context, tenantID int64) (int64, error)
	// Jejak aksi admin. metadata TANPA PII (id saja, bukan email/nama).
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// Undangan bergabung ke workspace. token = rahasia URL (crypto/rand hex via
	// oauth.NewState). email boleh milik orang yang BELUM punya akun.
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	// Jadikan user anggota workspace dgn role tertentu. Dipakai: register/OAuth (owner
	// workspace pertama), buat workspace baru (owner), terima invite (admin/member).
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	// User baru dari OAuth: tanpa password, email terverifikasi provider, + avatar.
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	// Buat tenant baru (dipanggil saat register/oauth user baru — 1 user = 1 tenant).
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// users = tabel GLOBAL (identitas murni, TANPA tenant/role — keduanya pindah ke
	// memberships). Keanggotaan dibuat terpisah via CreateMembership dalam tx sama.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Batalkan undangan yang belum diterima.
	DeleteInvite(ctx context.Context, arg DeleteInviteParams) error
	// Keluarkan anggota dari workspace (atau user keluar sendiri).
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	// Jalur PUBLIK (/invite/{token}) — penerima belum tentu login/anggota. Validasi
	// kedaluwarsa & sudah-dipakai dilakukan di handler agar pesannya spesifik.
	GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error)
	// Validasi keanggotaan — dipakai middleware Scope SEBELUM membuka tx ber-tenant
	// (memastikan tenant aktif di session memang milik user; anti tenant-forcing).
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetTenant(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUser(ctx context.Context, id int64) (User, error)
	// Soft-delete gotcha: user terhapus tak boleh login.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Cek apakah email = operator platform (staff). Dipakai RefreshIdentity untuk
	// menentukan bypass RLS (is_super) + role platform. super_admin TIDAK di sini
	// (env-only via SUPER_ADMIN_EMAILS).
	IsPlatformStaff(ctx context.Context, email string) (bool, error)
	ListAuditLogs(ctx context.Context, pageSize int32) ([]AuditLog, error)
	// Login/logout terbaru (subset audit_logs) untuk tabel aktivitas panel.
	ListAuthEvents(ctx context.Context, pageSize int32) ([]AuditLog, error)
	// Undangan PENDING satu workspace (panel anggota) — yang sudah diterima disaring.
	ListInvitesByTenant(ctx context.Context, tenantID int64) ([]Invite, error)
	// Daftar anggota SATU workspace (panel /admin/members). JOIN users untuk email
	// tampilan — users kini tabel global (tanpa RLS), jadi filter tenant di sini.
	ListMembersByTenant(ctx context.Context, tenantID int64) ([]ListMembersByTenantRow, error)
	// Daftar workspace milik user (untuk switcher sidebar). Urut terlama dulu agar
	// workspace pertama (dari register) jadi default stabil.
	ListMembershipsByUser(ctx context.Context, userID int64) ([]ListMembershipsByUserRow, error)
	// Membership BANYAK user sekaligus (panel /dev: tampilkan workspace+role tiap
	// user). Satu query untuk semua id → hindari N+1 (Rule 13).
	ListMembershipsForUsers(ctx context.Context, userIds []int64) ([]ListMembershipsForUsersRow, error)
	ListOAuthAccountsByUser(ctx context.Context, userID int64) ([]OauthAccount, error)
	ListPlatformStaff(ctx context.Context) ([]PlatformStaff, error)
	// Panel /dev: keyset pagination, hanya user aktif (belum soft-delete).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Tren per HARI-LOKAL untuk rentang mingguan/bulanan (line chart).
	PresenceByDay(ctx context.Context, arg PresenceByDayParams) ([]PresenceByDayRow, error)
	// Distribusi aktivitas per JAM-LOKAL untuk satu rentang (bar "aktivitas per jam").
	// AT TIME ZONE mengonversi bucket UTC ke jam lokal. Handler mengisi jam kosong
	// jadi 0 (sumbu X ECharts butuh 0..23 lengkap). COALESCE+cast: SUM/COUNT nullable
	// → paksa int64 (bukan pgtype.Numeric).
	PresenceByHour(ctx context.Context, arg PresenceByHourParams) ([]PresenceByHourRow, error)
	// KPI ringkas untuk stat cards pada rentang aktif.
	PresenceKPIs(ctx context.Context, arg PresenceKPIsParams) (PresenceKPIsRow, error)
	// "User aktif jam berapa s/d jam berapa" untuk rentang: first/last seen per user +
	// total hit. JOIN users untuk email TAMPILAN panel (dev-only UI, bukan log — tabel
	// activity_presence sendiri hanya simpan user_id). first/last dikembalikan sebagai
	// timestamptz UTC; handler memformatnya ke jam lokal (appTZ) — lebih bersih dari
	// AT TIME ZONE di SQL (yang bikin sqlc emit interface{}).
	PresenceUserSpans(ctx context.Context, arg PresenceUserSpansParams) ([]PresenceUserSpansRow, error)
	// Presence bucket 15-menit. bucket_at di-floor SERVER-SIDE ke kelipatan 900 dtk
	// (jangan hitung di Go — hindari drift clock). Agregasi di level baris: request
	// berulang dalam bucket sama hanya menaikkan hits, bukan insert baris baru.
	RecordPresence(ctx context.Context, arg RecordPresenceParams) error
	RemovePlatformStaff(ctx context.Context, email string) error
	SoftDeleteUser(ctx context.Context, id int64) error
	// Cek ketersediaan slug (untuk auto-suffix unik: acme -> acme-2 -> ...).
	TenantSlugExists(ctx context.Context, slug string) (bool, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	// Ganti NAMA tampilan workspace (owner-only, di-guard di handler). Slug SENGAJA
	// tak diubah — immutable setelah dibuat (stabilitas URL; ganti display != ganti URL).
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	// URL avatar Google berubah saat user ganti foto → update tiap login.
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	// Kuota workspace per user (override platform; default dari MAX_WORKSPACES_PER_USER).
	UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
