// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Authz ownership: filter user_id, bukan cuma id.
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) error
	GetTodo(ctx context.Context, arg GetTodoParams) (Todo, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Keyset pagination. Halaman pertama: kirim cursor (created_at, id) = nilai maksimum
	// ('infinity'::timestamptz, maxint) agar seluruh baris memenuhi syarat.
	// Halaman berikutnya: kirim (created_at, id) baris TERAKHIR yang tampil.
	// Cast eksplisit ::bigint pada cursor_id: tanpa ini sqlc salah infer tipe cursor_id
	// (mengikuti created_at) dari row-value comparison. Cast memaksa int64.
	ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error)
}

var _ Querier = (*Queries)(nil)
