// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddPlatformStaff(ctx context.Context, email string) (PlatformStaff, error)
	// Jejak aksi admin. metadata TANPA PII (id saja, bukan email/nama).
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	// User baru dari OAuth: tanpa password, email terverifikasi provider, + avatar.
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	// Buat tenant baru (dipanggil saat register/oauth user baru — 1 user = 1 tenant).
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// tenant_id WAJIB di INSERT (RLS WITH CHECK). Pemanggil (register) sudah tahu
	// tenant dari tenant yang baru dibuat.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetTenant(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUser(ctx context.Context, id int64) (User, error)
	// Soft-delete gotcha: user terhapus tak boleh login.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Cek apakah email = operator platform (staff). Dipakai RefreshIdentity untuk
	// menentukan bypass RLS (is_super) + role platform. super_admin TIDAK di sini
	// (env-only via SUPER_ADMIN_EMAILS).
	IsPlatformStaff(ctx context.Context, email string) (bool, error)
	ListAuditLogs(ctx context.Context, pageSize int32) ([]AuditLog, error)
	// Login/logout terbaru (subset audit_logs) untuk tabel aktivitas panel.
	ListAuthEvents(ctx context.Context, pageSize int32) ([]AuditLog, error)
	ListOAuthAccountsByUser(ctx context.Context, userID int64) ([]OauthAccount, error)
	ListPlatformStaff(ctx context.Context) ([]PlatformStaff, error)
	// Panel /dev: keyset pagination, hanya user aktif (belum soft-delete).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Tren per HARI-LOKAL untuk rentang mingguan/bulanan (line chart).
	PresenceByDay(ctx context.Context, arg PresenceByDayParams) ([]PresenceByDayRow, error)
	// Distribusi aktivitas per JAM-LOKAL untuk satu rentang (bar "aktivitas per jam").
	// AT TIME ZONE mengonversi bucket UTC ke jam lokal. Handler mengisi jam kosong
	// jadi 0 (sumbu X ECharts butuh 0..23 lengkap). COALESCE+cast: SUM/COUNT nullable
	// → paksa int64 (bukan pgtype.Numeric).
	PresenceByHour(ctx context.Context, arg PresenceByHourParams) ([]PresenceByHourRow, error)
	// KPI ringkas untuk stat cards pada rentang aktif.
	PresenceKPIs(ctx context.Context, arg PresenceKPIsParams) (PresenceKPIsRow, error)
	// "User aktif jam berapa s/d jam berapa" untuk rentang: first/last seen per user +
	// total hit. JOIN users untuk email TAMPILAN panel (dev-only UI, bukan log — tabel
	// activity_presence sendiri hanya simpan user_id). first/last dikembalikan sebagai
	// timestamptz UTC; handler memformatnya ke jam lokal (appTZ) — lebih bersih dari
	// AT TIME ZONE di SQL (yang bikin sqlc emit interface{}).
	PresenceUserSpans(ctx context.Context, arg PresenceUserSpansParams) ([]PresenceUserSpansRow, error)
	// Presence bucket 15-menit. bucket_at di-floor SERVER-SIDE ke kelipatan 900 dtk
	// (jangan hitung di Go — hindari drift clock). Agregasi di level baris: request
	// berulang dalam bucket sama hanya menaikkan hits, bukan insert baris baru.
	RecordPresence(ctx context.Context, arg RecordPresenceParams) error
	RemovePlatformStaff(ctx context.Context, email string) error
	SoftDeleteUser(ctx context.Context, id int64) error
	// URL avatar Google berubah saat user ganti foto → update tiap login.
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
