// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, updated_at, updated_by FROM platform_settings WHERE key = $1
`

// Baca satu pengaturan platform. Tak ditemukan = keadaan SAH (pemanggil jatuh ke
// default bawaan kode), bukan error yang perlu diributkan.
func (q *Queries) GetSetting(ctx context.Context, key string) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i PlatformSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, updated_at, updated_by FROM platform_settings ORDER BY key
`

// Semua pengaturan sekaligus — dipakai halaman /dev/settings dan pemuatan cache
// saat boot. Jumlahnya sedikit, jadi tak dipaginasi (beda dari daftar user).
func (q *Queries) ListSettings(ctx context.Context) ([]PlatformSetting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformSetting{}
	for rows.Next() {
		var i PlatformSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO platform_settings (key, value, updated_by, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = now()
`

type UpsertSettingParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedBy *int64 `json:"updated_by"`
}

// Simpan pengaturan. UPSERT karena baris mungkin belum ada (deployment baru yang
// tak menjalankan seed): pemanggil tak perlu tahu bedanya.
func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
