// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package db

import (
	"context"
)

const addPlatformStaff = `-- name: AddPlatformStaff :one
INSERT INTO platform_staff (email) VALUES ($1)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, created_at
`

func (q *Queries) AddPlatformStaff(ctx context.Context, email string) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, addPlatformStaff, email)
	var i PlatformStaff
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const isPlatformStaff = `-- name: IsPlatformStaff :one
SELECT EXISTS (SELECT 1 FROM platform_staff WHERE email = $1)::boolean
`

// Cek apakah email = operator platform (staff). Dipakai RefreshIdentity untuk
// menentukan bypass RLS (is_super) + role platform. super_admin TIDAK di sini
// (env-only via SUPER_ADMIN_EMAILS).
func (q *Queries) IsPlatformStaff(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isPlatformStaff, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listPlatformStaff = `-- name: ListPlatformStaff :many
SELECT id, email, created_at FROM platform_staff ORDER BY created_at DESC
`

func (q *Queries) ListPlatformStaff(ctx context.Context) ([]PlatformStaff, error) {
	rows, err := q.db.Query(ctx, listPlatformStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformStaff{}
	for rows.Next() {
		var i PlatformStaff
		if err := rows.Scan(&i.ID, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlatformStaff = `-- name: RemovePlatformStaff :exec
DELETE FROM platform_staff WHERE email = $1
`

func (q *Queries) RemovePlatformStaff(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, removePlatformStaff, email)
	return err
}
