// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, status, created_at
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Buat tenant baru (dipanggil saat register/oauth user baru — 1 user = 1 tenant).
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, status, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, status, created_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const tenantSlugExists = `-- name: TenantSlugExists :one
SELECT EXISTS (SELECT 1 FROM tenants WHERE slug = $1)::boolean
`

// Cek ketersediaan slug (untuk auto-suffix unik: acme -> acme-2 -> ...).
func (q *Queries) TenantSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, tenantSlugExists, slug)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenants SET name = $2 WHERE id = $1
`

type UpdateTenantParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Ganti NAMA tampilan workspace (owner-only, di-guard di handler). Slug SENGAJA
// tak diubah — immutable setelah dibuat (stabilitas URL; ganti display != ganti URL).
func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, updateTenant, arg.ID, arg.Name)
	return err
}
