// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQuotaOverrides = `-- name: CountQuotaOverrides :one
SELECT count(*)::bigint FROM users
WHERE workspace_quota IS NOT NULL AND deleted_at IS NULL
`

// Berapa user memegang HAK KHUSUS (kuota di-override, bukan mengikuti global).
// Dipakai halaman pengaturan untuk menyatakan dampak sebelum operator menyimpan:
// mereka SENGAJA tak ikut berubah, dan tanpa angka ini operator mengira
// pengaturannya tak bekerja.
func (q *Queries) CountQuotaOverrides(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotaOverrides)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (email, email_verified, avatar_url)
VALUES ($1, true, $2)
RETURNING id, email, pass_hash, email_verified, status, avatar_url, deleted_at, workspace_quota, created_at
`

type CreateOAuthUserParams struct {
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
}

// User baru dari OAuth: tanpa password, email terverifikasi provider, + avatar.
func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser, arg.Email, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PassHash,
		&i.EmailVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.WorkspaceQuota,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, pass_hash)
VALUES ($1, $2)
RETURNING id, email, pass_hash, email_verified, status, avatar_url, deleted_at, workspace_quota, created_at
`

type CreateUserParams struct {
	Email    string  `json:"email"`
	PassHash *string `json:"pass_hash"`
}

// users = tabel GLOBAL (identitas murni, TANPA tenant/role — keduanya pindah ke
// memberships). Keanggotaan dibuat terpisah via CreateMembership dalam tx sama.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PassHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PassHash,
		&i.EmailVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.WorkspaceQuota,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, pass_hash, email_verified, status, avatar_url, deleted_at, workspace_quota, created_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PassHash,
		&i.EmailVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.WorkspaceQuota,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, pass_hash, email_verified, status, avatar_url, deleted_at, workspace_quota, created_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

// Soft-delete gotcha: user terhapus tak boleh login.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PassHash,
		&i.EmailVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.WorkspaceQuota,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, pass_hash, email_verified, status, avatar_url, deleted_at, workspace_quota, created_at FROM users
WHERE deleted_at IS NULL
  AND (created_at, id) < ($1::timestamptz, $2::bigint)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListUsersParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

// Panel /dev: keyset pagination, hanya user aktif (belum soft-delete).
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PassHash,
			&i.EmailVerified,
			&i.Status,
			&i.AvatarUrl,
			&i.DeletedAt,
			&i.WorkspaceQuota,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_url = $2 WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID        int64   `json:"id"`
	AvatarUrl *string `json:"avatar_url"`
}

// URL avatar Google berubah saat user ganti foto → update tiap login.
func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	return err
}

const updateUserQuota = `-- name: UpdateUserQuota :exec
UPDATE users SET workspace_quota = $2 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserQuotaParams struct {
	ID             int64  `json:"id"`
	WorkspaceQuota *int32 `json:"workspace_quota"`
}

// Kuota workspace per user. NULL = IKUT DEFAULT GLOBAL (platform_settings), angka
// = hak khusus milik user itu yang kebal perubahan global. Membedakan keduanya
// adalah alasan kolom ini nullable — dgn NOT NULL, "kebetulan 3" tak bisa
// dibedakan dari "sengaja diberi 3".
func (q *Queries) UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error {
	_, err := q.db.Exec(ctx, updateUserQuota, arg.ID, arg.WorkspaceQuota)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
